### PR TITLE
Added Ukrainian and Russian translation, and some fix

### PR DESCRIPTION
**Pull request by putsan**
Added Ukrainian and Russian translation, and some fix.
Did I do the right thing?
How can I transfer other items?

### CODE REVIEW

**Comment by krixano** [comment]
Yes, I will add the languages to the language selection. I will also Add a way to change languages in settings. Thanks! The only thing is it would have been better that this was merged to Develop branch instead of master but you might have to redo stuff again. So, I will figure it out so you don't have to.

**Comment by krixano** [comment]
Actually, I think I might be able to merge this into both master and develop.

**Comment by imachug** [comment]
Russian is `Русский`

**Comment by putsan** [comment]
@krixano 
Ukrainian (uk) is `Українська`
Russian (ru) is `Русский`
and

> The only thing is it would have been better that this was merged to Develop branch instead of master but you might have to redo stuff again.

I can do this if needed

**Comment by krixano** [comment]
@putsan No. I'll just merge it into both master and develop.

**Comment by krixano** [comment]
@putsan Thanks for the translations!

**Pull request merged**
